name: CI/CD Pipeline

on:
  create:  # Triggered when a branch or tag is created
  push:
    branches:
      - '*'
      - '!master'
      - '!release/**'
      - '!feature/**'
  pull_request:
    branches:
      - develop
      - master
      - 'release/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'prod'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code
        run: echo "Running linters..."
      - name: Run Tests
        run: echo "Running tests..."

  build-and-push-image:
    needs: lint-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/release/') || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image
        run: |
          echo "Building Docker image..."
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            IMAGE_TAG="latest"
          elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            IMAGE_TAG="${GITHUB_REF#refs/heads/release/}"
          elif [ "${{ github.ref }}" == "refs/heads/master" ]; then
            IMAGE_TAG="stable"
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            IMAGE_TAG="${GITHUB_REF#refs/tags/}"
          else
            IMAGE_TAG="sha-${GITHUB_SHA}"
          fi
          echo "Pushing Docker image to registry with tag $IMAGE_TAG"
          # Add Docker build and push commands here using $IMAGE_TAG

  deploy-to-develop:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to development environment
        run: echo "Deploying to development environment..."

  deploy-to-staging:
    if: startsWith(github.ref, 'refs/heads/release/') && github.event_name == 'push'
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to staging environment
        run: |
          echo "Deploying to staging environment..."
          VERSION_TAG=${GITHUB_REF#refs/heads/release/}
          echo "Version tag is $VERSION_TAG"

  deploy-to-production:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image for production
        run: echo "Building Docker image for prod..."
      - name: Push to Docker Registry
        run: echo "Pushing Docker image to registry for prod..."
      - name: Deploy to production environment
        run: echo "Deploying to production environment..."
