name: CI/CD Workflow

on:
  push:
    branches:
      - 'feature/**'
      - develop
      - staging
      - master

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Lint Code
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: echo "Linting the code on feature branch"
      
      - name: Run Tests
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: echo "Running tests on feature branch"
  
  build-and-push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: |
      github.ref == 'refs/heads/develop' || 
      github.ref == 'refs/heads/staging' || 
      github.ref == 'refs/heads/master'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Simulate Building Docker image
        run: echo "Building Docker image for ${GITHUB_REF#refs/heads/}"

      - name: Simulate Pushing Docker image to Registry
        run: echo "Pushing Docker image to registry for ${GITHUB_REF#refs/heads/}"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-push
    if: |
      github.ref == 'refs/heads/develop' ||
      github.ref == 'refs/heads/staging' || 
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Simulate Deploy to Development Environment
        if: github.ref == 'refs/heads/develop'
        run: echo "Deploying to development environment"
      
      - name: Simulate Deploy to Staging Environment
        if: github.ref == 'refs/heads/staging'
        run: echo "Deploying to staging environment"
      
      - name: Simulate Manual Deploy to Production Environment
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master'
        run: echo "Deploying to production environment"
