# .github/workflows/ci.yml
name: Continuous Integration

on:
  push:
    branches:
      - '**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code
        run: echo "Running linters for all branches"
      - name: Run Tests
        run: echo "Running tests for all branches"
