# .github/workflows/dev_cd.yml
name: Develop Deployment

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: echo "Building Docker image tagged as latest:${GITHUB_SHA}"
      - name: Push Docker Image to Registry
        run: echo "Pushing Docker image with tag latest:${GITHUB_SHA}"
      - name: Deploy to Kubernetes
        run: echo "Deploying to development environment with tag latest:${GITHUB_SHA}"
