# .github/workflows/prod_cd.yml
name: Production Deployment

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag of the Docker image to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Kubernetes
        run: echo "Deploying to production environment with tag ${{ github.event.inputs.image_tag }}"
