# .github/workflows/staging_cd.yml
name: Staging Deployment

on:
  push:
    branches:
      - 'release/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: echo "Building Docker image tagged as release:${GITHUB_SHA}"
      - name: Push Docker Image to Registry
        run: echo "Pushing Docker image with tag release:${GITHUB_SHA}"
      - name: Deploy to Kubernetes
        run: echo "Deploying to staging environment with tag release:${GITHUB_SHA}"